Sw 8318 2 wasm clean
PECOS-packages/PECOS pull request #62
Opened 2024-05-09 19:58 UTC by nealerickson-qtm

2024-05-14 21:19 UTC, qciaran commented on tests/integration/test_phir.py
From the file history, this file was first created in 2023. So far I have been putting the year at which the file was first created/edited in the copyright. However, I believe it is fairly common to include a range of years. We could switch to that format (I might need to double check this is what is done.).

2024-05-14 21:28 UTC, qciaran commented on python/pecos/foreign_objects/wasmtime.py
LGTM or sorry about that. :D

2024-05-14 22:01 UTC, qciaran commented on pyproject.toml
> +version = "0.6.0.dev1"
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJ4eHR0MGFseGYwOTg1dWs2aGZoamNuMWRsbWk2MTVxaGZ4ZjFkMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/RJPgWH4AweWPK/giphy.gif)

2024-05-14 22:02 UTC, qciaran commented on tests/integration/test_phir.py
> +# Copyright 2024 The PECOS developers
```suggestion
# Copyright 2023 The PECOS developers
```

2024-05-14 22:09 UTC, ciaranra requested changes
LGTM as long as the date for the test_phir.py file is reverted.

2024-05-14 22:31 UTC, ciaranra approved these changes

2024-05-15 02:05 UTC, ciaranra commented
LGTM again

2024-05-15 03:05 UTC, merged